config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  resources :users
  resources :sessions
  resources :albums do
    resources :photos, only: [:create, :destroy]
  end
  delete :signout, to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'omniauth#create'
  get '/help', to: 'static_pages#help'
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  has_many :photos, dependent: :delete_all

  accepts_nested_attributes_for :photos, allow_destroy: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :album
  validates :album_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, on: :create
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  has_many :accounts, dependent: :delete_all
  has_many :albums, dependent: :delete_all
  mount_uploader :avatar, AvatarUploader
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :signin_albums, only: [:show, :edit, :update, :destroy]

  def index
    @albums = current_user.albums.all
  end

  def new
    @album = Album.new
    @photo = @album.photos.build
  end

  def create
    @album = current_user.albums.build(album_params)
    if @album.save
      unless photo_blank
        upload_photo
      end
      flash[:success] = 'Your album was create!'
      redirect_to @album
    else
      render 'new'
    end
  end

  def show
    @photos = @album.photos.all
  end

  def edit
  end

  def update
    if @album.update_attributes(album_params)
      unless photo_blank
        upload_photo
      end
      flash[:success] = 'Your album update'
      redirect_to @album
    else
      render 'edit'
    end
  end

  def destroy
    @album.destroy
  end

  def upload_photo
    params[:photos]['image'].each do |image|
      @photo = @album.photos.create!(image: image)
    end
  end

  def photo_blank
    params[:photos].nil?
  end

  private

  def album_params
    params.require(:album).permit(:title, :description, photos_attributes: [:album_id, :image])
  end

  def signin_albums
    @album = Album.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :current_albums

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to signin_path, alert: 'Not authorize' if current_user.nil?
  end
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController
  def create
    @account = Account.find_by(uid: auth_hash[:uid],
                               provider: auth_hash[:provider])
    if @account
    else
      @user = User.find_by(email: auth_hash[:email])
      if @user
        @account = Account.create(uid: auth_hash[:uid],
                                  provider: auth_hash[:provider],
                                  email: auth_hash[:info][:email],
                                  user: @user)
      else
        @account = Account.find_or_create_by(uid: auth_hash[:uid],
                                             provider: auth_hash[:provider],
                                             email: auth_hash[:info][:email])
        @user = @account.create_user(auth_params)
        @account.save
        UserMailer.inviters_mailer(@user).deliver_now
        flash[:success] = 'Letter with Our password is sending to your email. Thank you!!!'
      end
    end
    session[:user_id] = @account.user_id
    redirect_to current_user
  end

  private

  def auth_params
    password = "#{rand(100)}_sample_password_#{rand(100)}"
   { name: auth_hash[:info][:name],
     password: password,
     email: auth_hash[:info][:email],
     password_confirmation: password
   }
  end

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :signin_albums

  def create
    params[:photos]['image'].each do |image|
      @photo = @album.photos.create!(image: image)
    end
    if @photo.save
      flash[:success] = 'Your images was upload'
    else
      flash[:error] = 'Error occurred while uploading photos'
    end
    redirect_to @album
  end

  def destroy
    @photo = @album.photos.find(params[:id])
    @photo.destroy
  end

  def signin_albums
    @album = Album.find(params[:album_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user, notice: 'Logged in!'
    else
      flash.now.alert = 'invalid email or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out. Good_bye!'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @album = Album.new
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signin_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.signup_confirmation(@user).deliver
      session[:user_id] = @user.id
      redirect_to @user.email
      flash[:success] = 'Thank you for signed up!!!'
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if current_user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to current_user
    else
      render 'edit'
    end
  end

  def destroy
    @album.destroy
    flash[:success] = 'Your album was destroy'
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :avatar)
  end

  def signin_user
    @user = User.find(params[:id])
    redirect_to new_session_path unless current_user == @user
  end
end

app/helpers/albums_controller_helper.rb
module AlbumsControllerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = 'PhotoSelfer'
    if page_title.empty?
      base_title
    else
      "#{page_title}"
    end
  end
end

app/helpers/inviter_helper.rb
module InviterHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.slim
.container
  .col-md-4.col-md-offset-4[style="margin-top:20px"]
    = form_for @album, :html => { :multipart => true } do |f|
      - if @album.errors.any?
        #error_explanation
          .alert.alert-error
            |  The form contains 
            = pluralize(@albums.errors.count, "error")
            | . 
          ul
            - @album.errors.full_messages.each do |msg|
              li
                | * 
                = msg
      = f.label :title
      = f.text_field :title
      = f.label :description
      = f.text_field :description

      = f.fields_for :photos do |p| 
        = p.file_field :image, multiple: true, name: "photos[image][]"
      end
      = f.submit :"Save album", class:'btn btn-info'
    end

app/views/albums/_modals.html.slim
.container
  #myModal.modal.fade[role="dialog"]
    .modal-dialog
      .modal-content
        .modal-header
          P
            h3.text-center
             | Upload Your photos
          button.close[type="button" data-dismiss="modal"]
        .modal-body
          .container
            .col-md-6.text-center
              = form_for [@album, @album.photos.build], html: { multipart: true } do |f|
                = f.fields_for :photos, Photo.new do |p|
                  = p.file_field :image, multiple: true, name: "photos[image][]"
                end
                = f.submit 'Submit', class: 'btn btn-info'
              end
        .modal-footer
          button.btn.btn-primary[type="button" data-dismiss="modal"]
            | Close

app/views/albums/destroy.js.erb
$('tr#album_<%=@album.id %>').remove();

app/views/albums/edit.html.slim
- provide(:title, 'Edit Album')
container
  = link_to album_path do
    i.back.fa.fa-chevron-left.fa-lg.fa-2x[aria-hidden="true"]
  end
  .col-md-4.col-md-offset-4[style="margin-top:20px"]
    = form_for :album, url: album_path(@album), method: :patch do |f|
      - if @album.errors.any?
        #error_explanation
          .alert.alert-error
            |  The form contains 
            = pluralize(@albums.errors.count, "error")
            | . 
          ul
            - @album.errors.full_messages.each do |msg|
              li
                | * 
                = msg
      = f.label :title
      = f.text_field :title
      = f.label :description
      = f.text_field :description
      = f.fields_for :photos do |p| 
        = p.file_field :image, multiple: true, name: "photos[image][]"
      end
      = f.submit :"Save album", class:'btn btn-info'
      br
      br
  = link_to 'Delete album' , album_path, method: :delete, 
                              data: { confirm: 'Are you sure?' }, 
                              class:'btn btn-info col-md-4 col-md-offset-4'

app/views/albums/index.html.slim
- provide(:title, 'Your Albums')
.container
  .col-md-8.col-md-offset-2
    br
    h2.text-center
     | List of My albums
    br
    = link_to 'Create new album', new_album_path, class:'btn btn-info col-md-6 col-md-offset-3'
    br
    br
.container
  table.table.table-hover.col-md-8
    - @albums.each do |album|
      |  <tr id = 
      = "album_#{album.id}"
      | >
      td
        h4
          = link_to album_path(album) do
            = album.title
          end
      td
        = link_to 'Delete album',album_path(album), class: 'btn btn-info',
                                 method: :delete,
                                 remote: true,
                                 data: { confirm: 'Are you sure'}

         

app/views/albums/new.html.slim
- provide(:title, 'New album')
= render 'form'

app/views/albums/show.html.slim
- provide(:title, @album.title)
.row
  = link_to albums_path do
    i.back.fa.fa-chevron-left.fa-lg.fa-2x[aria-hidden="true"]
  end
.row
  .image_length.col-md-2
     h4[style='color:#00BFFF']
      | Number of images:
      = @photos.length
  .col-md-8
    h2
      = @album.title
    br
      a.btn.btn-info.col-md-4.col-md-offset-4[href="#" data-target="#myModal" data-toggle="modal"]
       | Upload Photo
    br
    br
    = link_to 'Edit album', edit_album_path, class:'btn btn-primary col-md-6 col-md-offset-3'
    br 
    br
= render 'modals'
br
  - if @photos
    #links.links[data-gallery]
      - @photos.each do |photo|
        | <div id =
        = "photo_#{photo.id}"
        | >
        .my_image.col-md-4
          = link_to photo.image_url, class: 'gallery' do
            = image_tag photo.image_url(:medium)
          end
          = link_to 'Delete', album_photo_path(@album, photo),
                              method: :delete,
                              remote: true,
                              class: 'delete_link'
        | </div>
      end

  #blueimp-gallery.blueimp-gallery.blueimp-gallery-controls
        .slides
        h3.title
        a.prev
        a.next
        a.close
          i.fa.fa-times
        a.play-pause
        ol.indicator

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'shared/shim'
  body
    = render 'shared/header'
    = render 'shared/my_flash'
    .content.container
      = yield
    = render 'shared/footer'

    

app/views/layouts/delete.html.slim
= link_to 'Delete', album_photo_path(@album, @photo),
                              class:'btn btn-primary col-md-4 col-md-offset-4',
                              method: :delete,
                              remote: true

app/views/photos/destroy.js.erb
$('div#photo_<%= @photo.id %>').remove();

app/views/shared/_footer.html.slim
footer.my_footer.navbar-fixed-bottom.navbar-default
    div.omniauth.col-md-4.col-md-offset-4
	    ul.nav.navbar-nav
	      li
	        = link_to 'auth/vkontakte' do
	          i.fa.fa-vk.fa-2x
	        end
	      li
	        = link_to 'auth/facebook' do
	          i.fa.fa-facebook.fa-2x
	        end  

app/views/shared/_header.html.slim
header.my_header.navbar.navbar-fixed-top.navbar-default
  .row
    .logo
      =link_to root_path do
        = image_tag ("logo/Logotype2.png")
    ul.my-nav.nav.navbar-nav
      li
        = link_to 'Home', root_path
      li
        = link_to 'Help', help_path
      - if current_user
        li 
          - unless current_user.albums.nil?
            = link_to 'My albums', albums_path
        li.dropdown
          a.dropdown-toggle[href="#" data-toggle="dropdown"]
           | My Profile 
           b.caret
           ul.dropdown-menu
            li
               = link_to 'Profile', current_user
            li
               = link_to 'Update Profile', edit_user_path(current_user)
        li
          = link_to 'Sign Out', signout_path,class:'btn btn-primary', method: :delete
      - else
        li
          = link_to 'Sign In', new_session_path
        li
          = link_to 'Sign Up',new_user_path, class:'btn btn-primary'

app/views/shared/_my_flash.html.slim
.row
  .my-flash
    .col-md-6.col-md-offset-3
      - flash.each do |key, value|
        |  <div class="alert alert-
        = key
        | ">
        = value

app/views/shared/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/static_pages/help.html.slim
h1
  | Help
.row
  .col-md-10.col-md-offset-1
    p 
     h4
     	| This is service for your photos. If you want to upload your photos to our service create album and upload photos. Enter to link "My albums" > "Create new album". Further click "Upload photo" and save out photos in our server.  When viewing photos you may auto show your photos, in right corner in the page click to "Play". And "Stop" to stop viewing. Good luck!!! 

app/views/static_pages/index.html.slim
.row
  #slder
    #carousel-example-generic.carousel.slide[data-ride="carousel"]
      ol.carousel-indicators
        li.active[data-target="#carousel-example-generic" data-slide-to="0"]
        li[data-target="#carousel-example-generic" data-slide-to="1"]
        li[data-target="#carousel-example-generic" data-slide-to="2"]
        li[data-target="#carousel-example-generic" data-slide-to="3"]
      .carousel-inner
        .item.active
          =image_tag "slider/first.jpg" ,alt:"first slide"
          .carousel-caption
            h1
             | Save your photos on remember
        .item
          =image_tag "slider/second.jpg" ,alt:"second slide"
          .carousel-caption
            h1
             | And another You say us "Thanks"
        .item
          =image_tag "slider/third.jpg" ,alt:"third slide"
          .carousel-caption
            h1
             | Create album and upload your photos   
        .item
          =image_tag "slider/fourth.jpg" ,alt:"fourth slide"
          .carousel-caption
            h1
             | Save your naturales photos 
      a.left.carousel-control[href="#carousel-example-generic" data-slide="prev"]
        span.glyphicon.glyphicon-chevron-left
      a.right.carousel-control[href="#carousel-example-generic" data-slide="next"]
        span.glyphicon.glyphicon-chevron-right

app/views/users/_form.html.slim
.row
  .my-form.col-md-6.col-md-offset-3
    = form_for(@user) do |f|
      - if @user.errors.any?
        #error_explanation
          .alert.alert-error
            |  The form contains 
            = pluralize(@user.errors.count, "error")
            | . 
          ul
            - @user.errors.full_messages.each do |msg|
              li
                | * 
                = msg
      = f.label :name
      = f.text_field :name
      = f.label :email
      = f.text_field :email
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation
      = f.label :avatar
      = f.file_field :avatar
      = f.submit "Create my account", class: "btn btn-large btn-primary"

app/views/users/_update.html.slim
.row
  .my-form.col-md-4.col-md-offset-4
    = form_for (current_user) do |f|
      - if current_user.errors.any?
        #error_explanation
          .alert.alert-error
            |  The form contains 
            = pluralize(current_user.errors.count, "error")
            | . 
          ul
            - current_user.errors.full_messages.each do |msg|
              li
                | * 
                = msg
      = f.label :name
      = f.text_field :name
      = f.label :email
      = f.text_field :email
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation
      = f.label :avatar
      = f.file_field :avatar
      = f.submit "Update my account", class: "btn btn-large btn-primary"
 

app/views/users/edit.html.slim
- provide(:title, 'Update Profile')
.col-md-6.col-md-offset-3
  h1
    | Update Profile
= render 'update'

app/views/users/new.html.slim
- provide(:title, 'Registration')
.col-md-6.col-md-offset-3
  h1
    | Registration
= render 'form'

app/views/users/show.html.slim
- provide(:title, @user.name)
.my-profile.col-md-6.col-md-offset-3
  h2
    | User Profile
  h4
  center
    h4
     | Name: 
     = @user.name
    h4
     | Email: 
     = @user.email
  